### ISSUE TITLE
How YouTube works in your app ?

### ISSUE THREAD

**Issue by Tanmay-Gautam** [FirePlank/Student-Portal#24]
How YouTube works in your app ?

**Comment by FirePlank** [comment]
I used a lib called youtube-search-python. It made it easy.

**Comment by Tanmay-Gautam** [comment]
Thanks FirePlank for replying but I want to achieve this using tkinter or
pyqt5. I'm struggling to make it work but it's not working.

**Comment by Tanmay-Gautam** [comment]
Hi FirePlank/Student-Portal, I want to make a program that plays YouTube
video ( inspired by Student-Portal ) can you please teach me how can I do
this.

**Comment by FirePlank** [comment]
It doesn't matter if you use tkinter or smth else. It's the same result either way. The lib is very easy to use as well. You can look at the documentation oh how to use it or look at the code on this project for the YouTube app on how I did it. Thanks.

**Comment by Tanmay-Gautam** [comment]
Thanks, I'll check it out.

**Comment by Ahmed-otmani** [comment]
hey there!
can your program be converted into an apk file using Linux or a VM?

**Comment by Shiv-Patil** [comment]
> hey there!
> can your program be converted into an apk file using Linux or a VM?

Yes it certainly can be. In fact, I had made an apk for it.
However, it is meant to be a desktop and a desktop app only from the start, which is why it won't be a great experience. In my apk, the font scaling was totally off and there were quite a few bugs which I am sure can be fixed, but it's not worth it; It's only meant for desktop use.

**Comment by Ahmed-otmani** [comment]
I see, but i really thought it would be great if i could have the software on installed my phone for convenience :)

**Comment by Tanmay-Gautam** [comment]
Maybe you can just copy that project and make it compatible for Linux

**Comment by Shiv-Patil** [comment]
> Maybe you can just copy that project and make it compatible for Linux

It is compatible with Linux. There's even an executable for debian based linux distros in the releases.
