### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by abdimk** [FirePlank/Student-Portal#25]
could you tell me please ! how did you reduce the size of exe file in to 20 MB only ?  i have a project that the problem am facing https://github.com/abdimk/Graphene

**Comment by FirePlank** [comment]
The exe size depends on many factors like the amount of libraries it has to import or how complex the project is. So there is really no definite answer to your question as every project is different. What I have seen by personal experience though is that if I have compiled many projects with pyinstaller before it tends to import libraries from previous builds into new ones making the file size reduntantly big. To avoid this I suggest building your project within virtual enviorements to make sure pyinstaller is only including the libraries in the exe it needs.

Hope this helps you in anyway. Cheers!

**Comment by abdimk** [comment]
yea Thanks !
